# 0.1 numpy 튜토리얼
- Author: 오지환
- last updated : 2023-09-09

파이썬을 활용한 파생상품평가에 핵심이되는 numpy module에 대한 기본적인 개념에 대해서 설명한다.

NumPy(넘파이)는 파이썬의 수학적인 연산과 배열 데이터 처리를 위한 핵심 라이브러리이다. NumPy는 다차원 배열 객체와 배열 연산에 유용한 다양한 함수와 도구를 제공하여 데이터 과학, 수치 계산, 머신러닝 등 다양한 분야에서 널리 사용된. 파이썬의 기본 리스트와 비교하여 NumPy 배열은 더 효율적이고 강력한 연산을 수행할 수 있다. 

특히, 본 책의 파생상품평가에 있어서 매우 핵심적인 역할을 하는 라이브러리이다. 

본 책에서는 앞으로의 파이썬코드의 이해를 위하여 numpy의 매우 기초적인 내용만 다루며 앞으로 나올 예제들에 본 챕터에서 소개하지않는 함수들이 나올 수 있으며, 독자분들께서는 numpy 공식문서 혹은 타 numpy 관련 책들을 참고하면서 공부하기를 권장한다.

## numpy 다루기 
### 1. 배열생성기초
NumPy에서 배열은 ndarray(n-dimensional array)라는 객체로 표현됩니다.
'ndarray'는 'n-dimensional array'를 줄인 말로, '다차원 배열'을 의미합니다. 간단히 말하면, ndarray는 같은 종류의 데이터를 담을 수 있는 그리드(grid)라고 생각하면 됩니다. 이 그리드는 어떠한 차원으로도 구성될 수 있습니다.

In [3]:
import numpy as np

one_dimension_ndarray = np.array([1,2,3,4])
print(one_dimension_ndarray)
# 출력 :
"""
[1 2 3 4]
"""

[1 2 3 4]


'\n[1 2 3 4]\n'

일차원 배열 이외에도 2차원 배열, n차원 배열도 만들 수 있습니다.
다만, 설명의 편의상 2차원배열까지만 사용하도록 하겠습니다. 2차원배열은 흔히 알고계시는 엑셀의 테이블과 같은 형식이라고 이해하시면 됩니다.

In [4]:
two_dimension_ndarray = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(two_dimension_ndarray) 

# 출력 :
"""
[[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]]
"""

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


'\n[[1 2 3 4]\n[1 2 3 4]\n[1 2 3 4]\n[1 2 3 4]]\n'

### 2. 배열생성 - ones, zeros, random
np.zeros() 함수를 사용하여 모든 요소가 0인 배열을 생성하거나, np.ones() 함수를 사용하여 모든 요소가 1인 배열을 생성할 수 있다. 또한, 테이블의 크기만 알고, 각 요소에 random 값을 부여할 수도 있다. 


위와 같은 함수는 손쉽게 ndarray의 크기만 알면 배열을 생성해낼 수 있는 장점이 있다. 

In [5]:
# np.ones([2,4]) 란 2 x 4 배열의 크기를 가지며, 각각의 원소가 1인 ndarray를 생성한다. 
ones_two_dimension_ndarray = np.ones([2,4])
print(ones_two_dimension_ndarray) 
# 출력 :
"""

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

"""


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


'\n\n[[1. 1. 1. 1.]\n [1. 1. 1. 1.]]\n\n'

In [6]:
# np.zeros([3,4]) 란 3 x 4 배열의 크기를 가지며, 각각의 원소가 0인 ndarray를 생성합니다.
zeros_two_dimension_ndarray = np.zeros([3,4])
print(zeros_two_dimension_ndarray)

# 출력 :
"""

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
"""

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


'\n\n[[0. 0. 0. 0.]\n [0. 0. 0. 0.]\n [0. 0. 0. 0.]]\n \n'

In [7]:
# np.random.random([6,4]) 란 6 x 4 배열의 크기를 가지며, 각각의 원소가 0~1 랜덤값으로 초기화된 배열을 생성한다.
random_two_dimenstion_ndarray = np.random.random([6,4])
print(random_two_dimenstion_ndarray)

# 출력 :

"""
[[0.38492964 0.59845817 0.89110882 0.62985576]
 [0.72741048 0.13362749 0.08936951 0.24231004]
 [0.20380824 0.91635365 0.81887447 0.54764793]
 [0.20352367 0.84938552 0.42096778 0.81366777]
 [0.62183767 0.94082749 0.10839366 0.85757813]
 [0.18392468 0.07741452 0.56943393 0.68143676]]
"""


[[0.87361136 0.73591703 0.66174863 0.71448841]
 [0.81419162 0.67224283 0.97953647 0.40817546]
 [0.94139285 0.28823412 0.32047696 0.15599212]
 [0.54098125 0.04774757 0.62612184 0.79577023]
 [0.65879066 0.05040153 0.54560798 0.40463176]
 [0.81322221 0.98936953 0.59353944 0.24112469]]


'\n[[0.38492964 0.59845817 0.89110882 0.62985576]\n [0.72741048 0.13362749 0.08936951 0.24231004]\n [0.20380824 0.91635365 0.81887447 0.54764793]\n [0.20352367 0.84938552 0.42096778 0.81366777]\n [0.62183767 0.94082749 0.10839366 0.85757813]\n [0.18392468 0.07741452 0.56943393 0.68143676]]\n'

### 3. 배열 shape 확인
배열의 형상(shape)은 ndarray.shape 속성을 통해 확인할 수 있습니다. 해당 매트릭스의 크기를 알 수 있습니다.

In [8]:
print(ones_two_dimenstion_ndarray.shape)
# 2 x 4 행렬


NameError: name 'ones_two_dimenstion_ndarray' is not defined

In [9]:
print(zeros_two_dimenstion_ndarray.shape)
# 3 x 4 행렬

NameError: name 'zeros_two_dimenstion_ndarray' is not defined

### 4. 인덱싱 및 슬라이싱

인덱싱과 슬라이싱의 개념은 Python List를 다루는 문법에서도 다뤄지며, 동일한 방법으로 numpy에서도 ndarray를 다룰 수 있다.  

인덱싱과 슬라이싱은 NumPy 배열에서 특정 요소 또는 일부 요소에 접근하는 방법을 제공한다. 이를 통해 배열의 원하는 부분을 선택하거나 조작할 수 있다.  

인덱싱(Indexing)은 배열에서 특정 위치의 단일 요소에 접근하는 것이며, NumPy 배열의 인덱스는 0부터 시작하며, 각 차원마다 인덱스를 지정하여 접근한다. 

 


In [10]:
# 1차원 배열 인덱싱
array1d = np.array([1, 2, 3, 4, 5])
print(array1d[0])  # 출력: 1
print(array1d[2])  # 출력: 3

# 2차원 배열 인덱싱
array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d[0, 0])  # 출력: 1
print(array2d[1, 2])  # 출력: 6


1
3
1
6


 슬라이싱(Slicing)은 배열에서 일부 요소를 선택하며, 슬라이싱은 콜론(:)을 사용하여 구간을 지정하는 방식으로 수행된다. 사용자가 지정한 시작 인덱스부터 끝 인덱스 전까지의 요소를 선택할 수 있다. 

In [11]:
# 1차원 배열 슬라이싱
array1d = np.array([1, 2, 3, 4, 5])
print(array1d[1:4])  # 출력: [2 3 4]

# 2차원 배열 슬라이싱
array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d[:, 1])  # 출력: [2 5] (모든 행의 두 번째 열 선택)
print(array2d[1, :])  # 출력: [4 5 6] (두 번째 행의 모든 열 선택)
print(array2d[0:2, 1:3])  # 출력: [[2 3] [5 6]] (첫 번째부터 두 번째 행, 두 번째부터 세 번째 열 선택)


[2 3 4]
[2 5]
[4 5 6]
[[2 3]
 [5 6]]


### 5. 배열의 연산

NumPy는 배열 연산을 위한 다양한 함수와 기능을 제공한다. 기본적인 수학 연산인 덧셈, 뺄셈, 곱셈, 나눗셈은 NumPy 배열에서도 간단하게 수행할 수 있다.,배열 간 연산 시에는 브로드캐스팅(Broadcasting) 개념을 이해하면 보다 폭 넓은 연산이 가능한데, 이를 통해 배열 간의 크기가 다른 연산도 가능하게 하므로 향후 가치평가 로직을 만들 때, 코드의 이해를 위해서 필수적으로 이해해야만 한다.

#### 배열의 사칙연산

In [12]:
# 배열의 기본 연산
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# 덧셈
addition = array1 + array2
print(addition)  # 출력: [5 7 9]

# 뺄셈
subtraction = array1 - array2
print(subtraction)  # 출력: [-3 -3 -3]

# 곱셈
multiplication = array1 * array2
print(multiplication)  # 출력: [4 10 18]

# 나눗셈
division = array1 / array2
print(division)  # 출력: [0.25 0.4  0.5]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### 6. 브로드캐스팅(Broadcasting)

브로드캐스팅은 NumPy에서 배열 간의 크기가 다른 연산을 가능하게 하는 기능입니다. 작은 배열을 자동으로 확장하여 크기가 큰 배열과 동일한 모양을 만들어 연산을 수행한다.
1. 두 배열의 차원 수가 다르면, 차원 수가 작은 배열이 더 큰 배열의 차원 수와 맞을 때까지 1차원을 추가한다.
2. 두 배열의 차원 크기가 동일하지 않은 경우, 차원 크기가 1인 배열을 다른 배열과 동일한 크기로 확장한다.
3. 두 배열의 차원 크기가 동일한 경우, 해당 차원에서의 요소별 연산이 수행된다.

브로드캐스팅은 배열 간의 요소별 연산뿐만 아니라 스칼라와 배열 간의 연산에도 적용된다. 
스칼라는 크기가 1인 배열로 간주되며, 스칼라와 배열 간의 연산은 배열의 각 요소에 스칼라 값을 적용하는 것과 동일하다.

위의 이야기를 조금 더 구체화하면, 

1. 차원의 크기가 1일때 가능하다.
두 배열 간의 연산에서 최소한 하나의 배열의 차원이 1이라면(0번 축이든 1번 축이든; 1행이든 1열이든) 가능하다.
2. 차원의 짝이 맞을 때 가능하다.
차원에 대해 축의 길이가 동일하면 브로드캐스팅이 가능하다.

브로드캐스팅을 활용하면 배열의 크기가 다른 연산도 간편하게 수행할 수 있으며, 코드의 가독성과 효율성을 높일 수 있다.

In [13]:
import numpy as np

# 브로드캐스팅
array1 = np.array([1, 2, 3])
scalar = 2

# 스칼라와 배열의 곱셈
result = array1 * scalar # 3 x 1 배열과 , 1개 원소의 곱
print(result)  
# 출력: [2 4 6]

# 다차원 배열의 브로드캐스팅
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array3 = np.array([1, 2, 3])

# 배열 간의 덧셈
result = array2 + array3  # 3 x 2 배열과 3 x 1 배열의 덧셈
print(result)
# 출력:
# [[2 4 6]
#  [5 7 9]]

[2 4 6]
[[2 4 6]
 [5 7 9]]
